// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheaterReserveringenAPI.Data;

namespace TheaterReserveringenAPI.Migrations
{
    [DbContext(typeof(TheaterReserveringenAPIContext))]
    [Migration("20210326195631_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheaterReserveringenAPI.Models.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            KlantId = 1,
                            Adres = "Sesamstraat 1",
                            Email = "piet@puck.nl",
                            Naam = "Pietje Puk",
                            Woonplaats = "Hilversum"
                        },
                        new
                        {
                            KlantId = 2,
                            Adres = "Sesamstraat 2",
                            Email = "klaas@puck.nl",
                            Naam = "Klaas Vaak",
                            Woonplaats = "Hilversum"
                        },
                        new
                        {
                            KlantId = 3,
                            Adres = "Sesamstraat 3",
                            Email = "Gerda@puck.nl",
                            Naam = "Gerda Grutjes",
                            Woonplaats = "Hilversum"
                        });
                });

            modelBuilder.Entity("TheaterReserveringenAPI.Models.Reservering", b =>
                {
                    b.Property<int>("ReserveringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bezet")
                        .HasColumnType("bit");

                    b.Property<int?>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReserveringId");

                    b.HasIndex("KlantId");

                    b.ToTable("Reserveringen");

                    b.HasData(
                        new
                        {
                            ReserveringId = 1,
                            Bezet = false,
                            Naam = "A1"
                        },
                        new
                        {
                            ReserveringId = 2,
                            Bezet = false,
                            Naam = "A2"
                        },
                        new
                        {
                            ReserveringId = 3,
                            Bezet = false,
                            Naam = "A3"
                        },
                        new
                        {
                            ReserveringId = 4,
                            Bezet = false,
                            Naam = "A4"
                        },
                        new
                        {
                            ReserveringId = 5,
                            Bezet = false,
                            Naam = "A5"
                        },
                        new
                        {
                            ReserveringId = 6,
                            Bezet = false,
                            Naam = "A6"
                        },
                        new
                        {
                            ReserveringId = 7,
                            Bezet = false,
                            Naam = "B1"
                        },
                        new
                        {
                            ReserveringId = 8,
                            Bezet = false,
                            Naam = "B2"
                        },
                        new
                        {
                            ReserveringId = 9,
                            Bezet = false,
                            Naam = "B3"
                        },
                        new
                        {
                            ReserveringId = 10,
                            Bezet = false,
                            Naam = "B4"
                        },
                        new
                        {
                            ReserveringId = 11,
                            Bezet = false,
                            Naam = "B5"
                        },
                        new
                        {
                            ReserveringId = 12,
                            Bezet = false,
                            Naam = "B6"
                        },
                        new
                        {
                            ReserveringId = 13,
                            Bezet = false,
                            Naam = "C1"
                        },
                        new
                        {
                            ReserveringId = 14,
                            Bezet = false,
                            Naam = "C2"
                        },
                        new
                        {
                            ReserveringId = 15,
                            Bezet = false,
                            Naam = "C3"
                        },
                        new
                        {
                            ReserveringId = 16,
                            Bezet = false,
                            Naam = "C4"
                        },
                        new
                        {
                            ReserveringId = 17,
                            Bezet = false,
                            Naam = "C5"
                        },
                        new
                        {
                            ReserveringId = 18,
                            Bezet = false,
                            Naam = "C6"
                        },
                        new
                        {
                            ReserveringId = 19,
                            Bezet = false,
                            Naam = "D1"
                        },
                        new
                        {
                            ReserveringId = 20,
                            Bezet = false,
                            Naam = "D2"
                        },
                        new
                        {
                            ReserveringId = 21,
                            Bezet = false,
                            Naam = "D3"
                        },
                        new
                        {
                            ReserveringId = 22,
                            Bezet = false,
                            Naam = "D4"
                        },
                        new
                        {
                            ReserveringId = 23,
                            Bezet = false,
                            Naam = "D5"
                        },
                        new
                        {
                            ReserveringId = 24,
                            Bezet = false,
                            Naam = "D6"
                        },
                        new
                        {
                            ReserveringId = 25,
                            Bezet = false,
                            Naam = "E1"
                        },
                        new
                        {
                            ReserveringId = 26,
                            Bezet = false,
                            Naam = "E2"
                        },
                        new
                        {
                            ReserveringId = 27,
                            Bezet = false,
                            Naam = "E3"
                        },
                        new
                        {
                            ReserveringId = 28,
                            Bezet = false,
                            Naam = "E4"
                        },
                        new
                        {
                            ReserveringId = 29,
                            Bezet = false,
                            Naam = "E5"
                        },
                        new
                        {
                            ReserveringId = 30,
                            Bezet = false,
                            Naam = "E6"
                        });
                });

            modelBuilder.Entity("TheaterReserveringenAPI.Models.Reservering", b =>
                {
                    b.HasOne("TheaterReserveringenAPI.Models.Klant", "Klant")
                        .WithMany("Reserveringen")
                        .HasForeignKey("KlantId");
                });
#pragma warning restore 612, 618
        }
    }
}
